version: '3.8'

services:

  server:
    container_name: server
    build: ./server
    command: uvicorn server.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/server
    ports:
      - 8000:8000
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - pgdb
  
  pgdb:
    container_name: pgdb
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - pgdb
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"

volumes:
  pgdata: {} 
