version: '3.8'

services:

  server:
    container_name: server
    build: ./server
    command: uvicorn server.main:app --host ${MAIN_HOST} --reload
    volumes:
      - .:/server
    ports:
      - 8000:8000
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_HOST=${MAIN_HOST}
      - PG_PORT=${PG_PORT}
    depends_on:
      - pgdb
  
  pgdb:
    container_name: pgdb
    image: postgres:12
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - pgdb
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"

volumes:
  pgdata: {} 
